root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/worker ./cmd/worker"
entrypoint = ["./tmp/worker"]
include_ext = ["go", "sql"]
include_dir = [".."]
exclude_dir = ["tmp", "vendor", "../examples"]
exclude_regex = ["_test\\.go"]
delay = 300
stop_on_error = true
send_interrupt = true
kill_delay = "2s"

[log]
time = true

[color]
main = "magenta"
watch = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
